FROM  node:22.11.0

WORKDIR /app

COPY . .

RUN npm install

# Instala o Netcat (versão OpenBSD)
RUN apt-get update && apt-get install -y netcat-openbsd


# Copia o script de espera para o container
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh

COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/wait.sh","/start.sh"]